import Head from "next/head";
import { Builder, VisualComponents, Designer } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>CS Weeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav>Navigation</nav>

        <div id="app">
          <VisualComponents />
          <Builder />
          <Designer />
        </div>
      </main>
    </>
  );
}
